export { Home } from "./Home/home.page";
export { Shop } from "./Shop/shop.page";
export { AboutUs } from "./AboutUs/aboutus.page";
export { Service } from "./Services/services.page";
export { Blog } from "./Blog/blog.page";
export { Contact } from "./Contact/contact.page";
export { Cart } from "./Cart/cart.page";
export { Checkout } from "./Checkout/checkout.page";
export { ThankYouPage } from "./ThankYou/thankYou.page";
